import 'dart:convert';

import '../services/ssh_service.dart';
import '../models/printer_profile.dart';
import '../shell/shell_quoting.dart';

/// A `.deckhand-pre-<timestamp>` backup file discovered on the
/// printer. Generated by [_runWriteFile] right before a destructive
/// overwrite; this struct lets the wizard surface + restore them on a
/// subsequent run.
class DeckhandBackup {
  const DeckhandBackup({
    required this.originalPath,
    required this.backupPath,
    this.profileId,
    this.profileVersion,
    this.stepId,
    this.createdAt,
  });
  final String originalPath;
  final String backupPath;

  /// Sidecar metadata (when `.meta.json` was readable). Null means
  /// either the backup predates the sidecar feature, or the sidecar
  /// existed but didn't parse.
  final String? profileId;
  final String? profileVersion;
  final String? stepId;
  final DateTime? createdAt;
}

/// What the probe found for a single stack/screen install candidate.
/// `installed=true` iff the install path exists AND (when checkable)
/// its declared systemd unit is present. `active` reflects whether
/// the service is currently running, when there's one to check.
class InstallState {
  const InstallState({
    required this.installed,
    required this.active,
    this.path,
  });
  final bool installed;
  final bool active;
  final String? path;
}

/// Snapshot of what actually exists / runs on a specific printer,
/// captured in a single SSH round-trip. Used by wizard screens to
/// grey-out options that are already-clean (service not installed,
/// file already deleted, etc.) so the user's decisions reflect the
/// machine's state, not just the profile's abstract list.
///
/// Each inner map is keyed by the profile's declared `id`. A missing
/// id means we didn't probe for it (older profile, probe timeout); an
/// entry with `false` means we probed and it's absent/inactive.
class PrinterState {
  const PrinterState({
    required this.services,
    required this.files,
    required this.paths,
    required this.stackInstalls,
    required this.screenInstalls,
    required this.python311Installed,
    this.deckhandBackups = const [],
    this.osId,
    this.osCodename,
    this.osVersionId,
    this.pythonDefaultVersion,
    this.kernelRelease,
    this.probedAt,
  });

  final Map<String, ServiceRuntimeState> services;
  // File id -> "does at least one of its declared paths exist".
  final Map<String, bool> files;
  // Path id -> "does the path exist".
  final Map<String, bool> paths;
  // Stack-component id (moonraker, kiauh, crowsnest, fluidd, mainsail,
  // ...) -> InstallState. Lets the wizard tell "already installed" from
  // "user should pick".
  final Map<String, InstallState> stackInstalls;
  // Screen id -> InstallState. Same idea for profile.screens.
  final Map<String, InstallState> screenInstalls;
  final bool python311Installed;

  /// Deckhand-created `<target>.deckhand-pre-<timestamp>` backup files
  /// discovered on the printer. Surfaced so the wizard can offer to
  /// restore them before proceeding (e.g. a prior run overwrote
  /// `/etc/apt/sources.list` and the user wants it back).
  final List<DeckhandBackup> deckhandBackups;
  // From /etc/os-release. The profile often claims the printer is
  // still on the vendor-shipped OS, but users upgrade - we should key
  // conditional steps off what's actually there.
  final String? osId; // "debian", "ubuntu", "armbian"
  final String? osCodename; // "buster", "bookworm", "trixie"
  final String? osVersionId; // "10", "12", "13"
  final String? pythonDefaultVersion; // "3.7.3", "3.13.0"
  final String? kernelRelease; // `uname -r`
  // Null iff a probe hasn't run yet.
  final DateTime? probedAt;

  static const PrinterState empty = PrinterState(
    services: {},
    files: {},
    paths: {},
    stackInstalls: {},
    screenInstalls: {},
    python311Installed: false,
  );
}

class ServiceRuntimeState {
  const ServiceRuntimeState({
    required this.unitExists,
    required this.unitActive,
    required this.processRunning,
    required this.launcherScriptExists,
  });

  final bool unitExists;
  final bool unitActive;
  final bool processRunning;
  // launched_by.kind=script targets a file on disk. True iff that file
  // still exists - tells the UI whether this service is truly present
  // or is already-stripped vendor bloat.
  final bool launcherScriptExists;

  /// A service counts as "present" if ANY of its detection surfaces
  /// match. If nothing matches, the declaration in the profile is
  /// abstract-only for this specific machine and the UI can dim the
  /// option.
  bool get present =>
      unitExists || unitActive || processRunning || launcherScriptExists;
}

/// Builds the single shell script that captures all the state we
/// care about in one `ssh.run`. Output is a JSON-ish line-per-result
/// protocol that the parser on the Dart side expects.
///
/// Why a custom protocol instead of multiple round-trips: SSH
/// session setup over a pty-less dartssh2 run costs ~50-200 ms per
/// call; multiplying that by ~20 service + file checks quickly adds
/// up. One round-trip + a trivial parser is an order of magnitude
/// cheaper.
class PrinterStateProbe {
  PrinterStateProbe({required this.ssh});
  final SshService ssh;

  Future<PrinterState> probe({
    required SshSession session,
    required PrinterProfile profile,
  }) async {
    final script = _buildScript(profile);
    final res = await ssh.run(
      session,
      script,
      timeout: const Duration(seconds: 30),
    );
    // Non-zero exit is treated as "probe didn't work"; callers still
    // get a [PrinterState] but every field is conservatively false,
    // so screens fall back to showing all options (same behaviour as
    // before probing existed).
    return _parseReport(res.stdout);
  }

  String _buildScript(PrinterProfile profile) {
    final inv = profile.stockOs;
    final lines = <String>[
      '#!/bin/sh',
      // We can't rely on bash being /bin/sh on every distro, so stay
      // POSIX. Disable exit-on-error: we WANT every probe to run,
      // even if an earlier one fails. Set -u unset-var strictness
      // also avoided because some probes reference maybe-empty vars.
      'set +e',
      'say() { printf "%s\\t%s\\n" "\$1" "\$2"; }',
      // --------------------------------------------------------
      // OS identity. Profile's `os.stock` block is just a hint; the
      // live machine might be on an upgraded / different distro.
      // Steps that assume the stock OS (sources.list rewrites,
      // archive.debian.org fallbacks, etc.) MUST gate on these.
      // /etc/os-release is standard on every systemd distro.
      '. /etc/os-release 2>/dev/null',
      'say os:id "\${ID:-unknown}"',
      'say os:codename "\${VERSION_CODENAME:-unknown}"',
      'say os:version_id "\${VERSION_ID:-unknown}"',
      'say kernel "\$(uname -r 2>/dev/null || echo unknown)"',
      // --------------------------------------------------------
      // Python: default `python3` version (drives profile
      // python_min checks) + explicit 3.11 presence (drives the
      // python_rebuild_if_needed short-circuit).
      'if command -v python3 >/dev/null 2>&1; then',
      r'  say python:default "$(python3 -c "import sys;print(\".\".join(map(str,sys.version_info[:3])))" 2>/dev/null || echo unknown)"',
      'else',
      '  say python:default unknown',
      'fi',
      'command -v python3.11 >/dev/null 2>&1 && say python311 present || say python311 absent',
    ];
    for (final svc in inv.services) {
      final unit = _shellEscape(svc.raw['systemd_unit'] as String? ?? '');
      final proc = _shellEscape(svc.raw['process_pattern'] as String? ?? '');
      final launchedBy = (svc.raw['launched_by'] as Map?)
          ?.cast<String, dynamic>();
      final scriptPath = launchedBy != null && launchedBy['kind'] == 'script'
          ? (launchedBy['path'] as String? ?? '')
          : '';
      final qScript = _shellEscape(scriptPath);
      // `id` is inlined unquoted on purpose. Profile ids are already
      // constrained to `[a-z0-9_-]+` so there's nothing to escape,
      // and inlining them keeps the probe's wire format (`svc:<id>:
      // <facet>`) matching cleanly with the parser expectations.
      final id = svc.id;
      lines.addAll([
        '# $id',
        if (unit != "''")
          '( systemctl list-unit-files $unit >/dev/null 2>&1 && '
              'say svc:$id:unit_exists 1 ) || say svc:$id:unit_exists 0',
        if (unit != "''")
          '( systemctl is-active $unit >/dev/null 2>&1 && '
              'say svc:$id:unit_active 1 ) || say svc:$id:unit_active 0',
        if (proc != "''")
          '( pgrep -f $proc >/dev/null 2>&1 && '
              'say svc:$id:proc_running 1 ) || say svc:$id:proc_running 0',
        if (qScript != "''")
          '[ -e $qScript ] && say svc:$id:launcher_exists 1 || '
              'say svc:$id:launcher_exists 0',
      ]);
    }
    for (final f in inv.files) {
      final id = f.id;
      final paths = f.paths.map(_shellPathEscape).toList();
      // A file id is "present" if ANY of its declared paths exist.
      // Glob patterns: use `ls -d` and check exit; find-based probing
      // would be heavier and needs the pattern escaped differently.
      // `_shellPathEscape` handles `~/...` via `"$HOME/..."` - bash
      // won't expand `~` inside single-quoted `'~/foo'` so every
      // such check would always report 0.
      if (paths.isEmpty) {
        lines.add('say file:$id 0');
      } else {
        final test = paths.map((p) => 'ls -d $p >/dev/null 2>&1').join(' || ');
        lines.add('( $test ) && say file:$id 1 || say file:$id 0');
      }
    }
    for (final pth in inv.paths) {
      final id = pth.id;
      final path = _shellPathEscape(pth.path);
      lines.add('[ -e $path ] && say path:$id 1 || say path:$id 0');
    }
    // --------------------------------------------------------
    // Stack components: moonraker / kiauh / crowsnest / webui
    // choices. For each, check the install_path is present AND,
    // when a systemd unit is declared, that it's active.
    final stack = profile.stack;
    _addStackProbe(lines, 'moonraker', stack.moonraker);
    _addStackProbe(lines, 'kiauh', stack.kiauh);
    _addStackProbe(lines, 'crowsnest', stack.crowsnest);
    final webuiChoices = ((stack.webui?['choices'] as List?) ?? const [])
        .cast<Map>();
    for (final raw in webuiChoices) {
      final c = raw.cast<String, dynamic>();
      final id = c['id'] as String?;
      if (id == null) continue;
      _addStackProbe(lines, id, c);
    }
    // --------------------------------------------------------
    // Screens: profile.screens[*].install_path. Many screens are
    // just bundled directories with no systemd unit - we only check
    // install_path existence in that case.
    for (final sc in profile.screens) {
      final raw = sc.raw;
      final installPath =
          raw['install_path'] as String? ?? raw['source_path'] as String?;
      if (installPath == null) continue;
      final qPath = _shellPathEscape(installPath);
      lines.add(
        '[ -e $qPath ] && say screen:${sc.id}:installed 1 || say screen:${sc.id}:installed 0',
      );
      final unit = raw['systemd_unit'] as String?;
      if (unit != null && unit.isNotEmpty) {
        final qUnit = _shellEscape(unit);
        lines.add(
          '( systemctl is-active $qUnit >/dev/null 2>&1 && '
          'say screen:${sc.id}:active 1 ) || say screen:${sc.id}:active 0',
        );
      }
      lines.add('say screen:${sc.id}:path $qPath');
    }
    // --------------------------------------------------------
    // Deckhand backup discovery. Any `*.deckhand-pre-*` file under
    // the printer's config roots is a rollback opportunity. We search
    // /etc, /home, and /opt at up to depth 7 so nested printer_data
    // configs like /home/user/printer_data/config/macros/foo.cfg
    // aren't missed. The `.meta.json` sidecars (which also match the
    // wildcard) are filtered out so they don't show up as their own
    // restore offers.
    //
    // Busybox-compatible shell: `while IFS= read -r`, `printf`, `tr`,
    // `sed` (BRE mode -- not -E, which busybox sed doesn't have in
    // older builds). The two regexes are OR'd by running both `sed`
    // passes so either naming convention (tagged or legacy) is
    // stripped down to the original target path.
    //
    // Wire format: `backup\t<original>:::<backup>:::<meta-json-or-empty>`
    lines.add(
      // Search every location where a Deckhand-written file could
      // live. `/etc` + `/home` + `/opt` covers most stacks; adding
      // `/var` (for lib / cache / log configs that profiles may
      // rewrite), `/srv` (some printer images use it for Moonraker
      // data), and `/root` (if the SSH user escalates and ends up
      // writing config under root's home by mistake). -maxdepth 8
      // reaches typical deeply-nested `printer_data/config/macros/
      // category/foo.cfg` trees.
      //
      // `/root` requires elevation to read even with find - otherwise
      // the non-root SSH user gets EACCES silently and we'd miss any
      // backups under root's home. Wrap the /root search in a sudo
      // pass (falling back to empty output if sudo itself fails, so
      // we don't blow up the whole probe for non-sudoers users).
      "( find /etc /home /opt /var /srv -maxdepth 8 "
      "  -name '*.deckhand-pre-*' -not -name '*.meta.json' 2>/dev/null; "
      "  sudo -n find /root -maxdepth 8 "
      "  -name '*.deckhand-pre-*' -not -name '*.meta.json' 2>/dev/null "
      "    || true ) | "
      "while IFS= read -r f; do "
      "  orig=\"\$(printf '%s' \"\$f\" | "
      "    sed 's/\\.deckhand-pre-[A-Za-z0-9_-][A-Za-z0-9_-]*-[0-9][0-9]*\$//' | "
      "    sed 's/\\.deckhand-pre-[0-9][0-9]*\$//')\"; "
      "  meta=''; "
      "  if [ -r \"\$f.meta.json\" ]; then "
      "    meta=\$(tr '\\n\\t' '  ' < \"\$f.meta.json\" 2>/dev/null); "
      "  fi; "
      "  printf 'backup\\t%s:::%s:::%s\\n' \"\$orig\" \"\$f\" \"\$meta\"; "
      "done",
    );
    return lines.join('\n');
  }

  void _addStackProbe(
    List<String> lines,
    String id,
    Map<String, dynamic>? cfg,
  ) {
    if (cfg == null) return;
    final installPath = cfg['install_path'] as String?;
    if (installPath == null) return;
    final qPath = _shellPathEscape(installPath);
    lines.add(
      '[ -d $qPath ] && say stack:$id:installed 1 || say stack:$id:installed 0',
    );
    lines.add('say stack:$id:path $qPath');
    final unit = cfg['systemd_unit'] as String?;
    if (unit != null && unit.isNotEmpty) {
      final qUnit = _shellEscape(unit);
      lines.add(
        '( systemctl is-active $qUnit >/dev/null 2>&1 && '
        'say stack:$id:active 1 ) || say stack:$id:active 0',
      );
    }
  }

  /// Delegates to the canonical [shellPathEscape] in deckhand_core so
  /// tilde-prefixed paths stay safe against `$()`/backtick expansion in
  /// their suffix.
  String _shellPathEscape(String path) => shellPathEscape(path);

  PrinterState _parseReport(String stdout) {
    final services = <String, _ServiceAcc>{};
    final files = <String, bool>{};
    final paths = <String, bool>{};
    final stackAcc = <String, _InstallAcc>{};
    final screenAcc = <String, _InstallAcc>{};
    final backups = <DeckhandBackup>[];
    var python = false;
    String? osId;
    String? osCodename;
    String? osVersionId;
    String? pythonDefault;
    String? kernel;

    for (final rawLine in stdout.split('\n')) {
      final line = rawLine.trimRight();
      if (line.isEmpty) continue;
      final parts = line.split('\t');
      // Normal case: exactly one tab splitting key + value. Values
      // from the shell CAN contain literal tabs (file paths, rare but
      // legal); if we see extras we put them back into the value by
      // joining past index 0. This keeps path-with-tab cases from
      // silently dropping otherwise-valid rows.
      if (parts.length < 2) continue;
      final key = parts[0];
      final val = parts.length == 2 ? parts[1] : parts.skip(1).join('\t');
      if (key.isEmpty) continue;
      // Strip the leading/trailing double-quotes that /etc/os-release
      // fields arrive with. "debian" vs debian is the same to us.
      final unq = val.startsWith('"') && val.endsWith('"') && val.length >= 2
          ? val.substring(1, val.length - 1)
          : val;
      if (key == 'os:id') {
        osId = unq;
        continue;
      }
      if (key == 'os:codename') {
        osCodename = unq;
        continue;
      }
      if (key == 'os:version_id') {
        osVersionId = unq;
        continue;
      }
      if (key == 'kernel') {
        kernel = unq;
        continue;
      }
      if (key == 'python:default') {
        pythonDefault = unq;
        continue;
      }
      if (key == 'python311') {
        python = val == 'present';
        continue;
      }
      if (key.startsWith('svc:')) {
        final rest = key.substring(4);
        final idx = rest.lastIndexOf(':');
        if (idx < 0) continue;
        final id = rest.substring(0, idx);
        final facet = rest.substring(idx + 1);
        final acc = services.putIfAbsent(id, _ServiceAcc.new);
        final on = val == '1';
        switch (facet) {
          case 'unit_exists':
            acc.unitExists = on;
          case 'unit_active':
            acc.unitActive = on;
          case 'proc_running':
            acc.procRunning = on;
          case 'launcher_exists':
            acc.launcherExists = on;
        }
        continue;
      }
      if (key.startsWith('file:')) {
        files[key.substring(5)] = val == '1';
        continue;
      }
      if (key.startsWith('path:')) {
        paths[key.substring(5)] = val == '1';
        continue;
      }
      if (key.startsWith('stack:')) {
        _accumulateInstall(stackAcc, key.substring(6), val);
        continue;
      }
      if (key.startsWith('screen:')) {
        _accumulateInstall(screenAcc, key.substring(7), val);
        continue;
      }
      if (key == 'backup') {
        // Wire format: `<original>:::<backup>:::<meta-json-or-empty>`.
        // `:::` chosen because real paths never contain it. Meta is
        // the full JSON from the `.meta.json` sidecar (newlines + tabs
        // collapsed to spaces by the probe script so the payload fits
        // on one line).
        final parts = val.split(':::');
        if (parts.length < 2) continue;
        final original = parts[0].trim();
        final backupPath = parts[1].trim();
        if (original.isEmpty || backupPath.isEmpty) continue;
        final metaRaw = parts.length >= 3 ? parts[2] : '';
        String? profileId;
        String? profileVersion;
        String? stepId;
        DateTime? createdAt;
        if (metaRaw.trim().isNotEmpty) {
          try {
            final parsed = _stringKeyMap(jsonDecode(metaRaw));
            if (parsed != null) {
              profileId = _jsonString(parsed['profile_id']);
              profileVersion = _jsonString(parsed['profile_version']);
              stepId = _jsonString(parsed['step_id']);
              final iso = _jsonString(parsed['created_at_iso']);
              if (iso != null) {
                try {
                  createdAt = DateTime.parse(iso);
                } catch (_) {}
              }
              if (createdAt == null) {
                final ms = parsed['created_at_ms'];
                if (ms is num) {
                  createdAt = DateTime.fromMillisecondsSinceEpoch(
                    ms.toInt(),
                    isUtc: true,
                  );
                }
              }
            }
          } catch (_) {
            // Malformed JSON - ignore, backup still restorable.
          }
        }
        // Fall back to extracting timestamp from the filename when the
        // sidecar is missing (older Deckhand runs).
        createdAt ??= _backupTimestampAsDate(backupPath);
        backups.add(
          DeckhandBackup(
            originalPath: original,
            backupPath: backupPath,
            profileId: profileId,
            profileVersion: profileVersion,
            stepId: stepId,
            createdAt: createdAt,
          ),
        );
        continue;
      }
    }

    final svcState = {
      for (final e in services.entries)
        e.key: ServiceRuntimeState(
          unitExists: e.value.unitExists,
          unitActive: e.value.unitActive,
          processRunning: e.value.procRunning,
          launcherScriptExists: e.value.launcherExists,
        ),
    };

    return PrinterState(
      services: svcState,
      files: files,
      paths: paths,
      stackInstalls: {
        for (final e in stackAcc.entries)
          e.key: InstallState(
            installed: e.value.installed,
            active: e.value.active,
            path: e.value.path,
          ),
      },
      screenInstalls: {
        for (final e in screenAcc.entries)
          e.key: InstallState(
            installed: e.value.installed,
            active: e.value.active,
            path: e.value.path,
          ),
      },
      python311Installed: python,
      // Sort newest-first so the UI puts the most-recent restore
      // candidate at the top of the list. Prefer the sidecar's
      // `created_at` when available; fall back to the timestamp
      // extracted from the filename.
      deckhandBackups: [...backups]
        ..sort((a, b) {
          final at =
              a.createdAt?.millisecondsSinceEpoch ??
              _parseBackupTimestamp(a.backupPath) ??
              0;
          final bt =
              b.createdAt?.millisecondsSinceEpoch ??
              _parseBackupTimestamp(b.backupPath) ??
              0;
          return bt.compareTo(at);
        }),
      osId: osId,
      osCodename: osCodename,
      osVersionId: osVersionId,
      pythonDefaultVersion: pythonDefault,
      kernelRelease: kernel,
      probedAt: DateTime.now(),
    );
  }

  /// Extract the `<epoch_ms>` trailer off a deckhand backup path.
  /// Matches both the legacy `.deckhand-pre-<ts>` form and the
  /// profile-tagged `.deckhand-pre-<profile-id>-<ts>` form we emit
  /// now. Returns null on mismatch.
  static int? _parseBackupTimestamp(String backupPath) {
    final tagged = RegExp(
      r'\.deckhand-pre-[A-Za-z0-9_-]+-(\d+)$',
    ).firstMatch(backupPath);
    if (tagged != null) return int.tryParse(tagged.group(1)!);
    final legacy = RegExp(r'\.deckhand-pre-(\d+)$').firstMatch(backupPath);
    return legacy == null ? null : int.tryParse(legacy.group(1)!);
  }

  /// Convenience wrapper: parse + convert to DateTime.
  static DateTime? _backupTimestampAsDate(String backupPath) {
    final ms = _parseBackupTimestamp(backupPath);
    return ms == null
        ? null
        : DateTime.fromMillisecondsSinceEpoch(ms, isUtc: true);
  }

  /// Fold a single `stack:<id>:<facet>` or `screen:<id>:<facet>` probe
  /// line into its per-id accumulator. Unknown facets are ignored so
  /// the parser is forward-compatible with future probe additions.
  void _accumulateInstall(
    Map<String, _InstallAcc> accMap,
    String rest,
    String val,
  ) {
    final idx = rest.lastIndexOf(':');
    if (idx < 0) return;
    final id = rest.substring(0, idx);
    final facet = rest.substring(idx + 1);
    final acc = accMap.putIfAbsent(id, _InstallAcc.new);
    switch (facet) {
      case 'installed':
        acc.installed = val == '1';
      case 'active':
        acc.active = val == '1';
      case 'path':
        acc.path = val;
    }
  }

  String _shellEscape(String s) => shellSingleQuote(s);
}

String? _jsonString(Object? value) => value is String ? value : null;

Map<String, dynamic>? _stringKeyMap(Object? value) {
  if (value is! Map) return null;
  final out = <String, dynamic>{};
  for (final entry in value.entries) {
    final key = entry.key;
    if (key is String) out[key] = entry.value;
  }
  return out;
}

class _ServiceAcc {
  bool unitExists = false;
  bool unitActive = false;
  bool procRunning = false;
  bool launcherExists = false;
}

class _InstallAcc {
  bool installed = false;
  bool active = false;
  String? path;
}
